"""init-schema

Revision ID: b2364e79ddf4
Revises: bbaafe50b052
Create Date: 2025-03-24 21:36:20.188070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2364e79ddf4'
down_revision: Union[str, None] = 'bbaafe50b052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxon_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_with_author', sa.String(length=500), nullable=False),
    sa.Column('name_authorship', sa.String(length=500), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomenclatural_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typified_name', sa.String(length=50), nullable=False),
    sa.Column('taxon_name_id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], ),
    sa.ForeignKeyConstraint(['taxon_name_id'], ['taxon_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxon_concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxon_name_id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.id'], ),
    sa.ForeignKeyConstraint(['taxon_name_id'], ['taxon_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxon_concept')
    op.drop_table('nomenclatural_type')
    op.drop_table('taxon_name')
    op.drop_table('reference')
    # ### end Alembic commands ###
